import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#ffede3",
        "on-tertiary-container": "#353535",
        "on-primary": "#ffffff",
        "on-surface": "#231a13",
        "on-primary-container": "#453200",
        "error-container": "#ffdad6",
        tertiary: "#5f5e5e",
        background: "#fff8f5",
        "inverse-primary": "#e3c27e",
        "on-secondary": "#ffffff",
        "primary-fixed": "#ffdf9e",
        "on-tertiary-fixed": "#1c1b1b",
        error: "#ba1a1a",
        secondary: "#5f5e5b",
        "surface-container-high": "#f7e5da",
        "on-secondary-container": "#63635f",
        outline: "#7f7668",
        "surface-tint": "#745b21",
        surface: "#fff8f5",
        "on-surface-variant": "#4d4639",
        "on-primary-fixed": "#261a00",
        "on-tertiary": "#ffffff",
        "surface-container": "#fdeae0",
        "on-error": "#ffffff",
        "surface-container-low": "#fff1e9",
        "tertiary-container": "#9f9d9d",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#5a430a",
        "on-background": "#231a13",
        primary: "#745b21",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#1b1c19",
        "secondary-container": "#e1dfdb",
        "secondary-fixed": "#e4e2dd",
        "primary-container": "#b89a5a",
        "tertiary-fixed-dim": "#c8c6c5",
        "primary-fixed-dim": "#e3c27e",
        "inverse-surface": "#392e27",
        "surface-container-highest": "#f1dfd4",
        "on-secondary-fixed-variant": "#474744",
        "tertiary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c2",
        "on-tertiary-fixed-variant": "#474646",
        "outline-variant": "#d0c5b5",
        "surface-variant": "#f1dfd4",
        "surface-bright": "#fff8f5",
        "surface-dim": "#e8d7cc",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        gutter: "24px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-xl": "64px",
        "margin-desktop": "80px",
        "stack-lg": "32px",
        "margin-mobile": "20px",
      },
      maxWidth: {
        container: "1440px",
      },
      fontFamily: {
        "headline-md": ["var(--font-playfair)", "var(--font-noto-thai)", "serif"],
        "thai-support": ["var(--font-noto-thai)", "sans-serif"],
        "headline-lg": ["var(--font-playfair)", "var(--font-noto-thai)", "serif"],
        "display-lg": ["var(--font-playfair)", "var(--font-noto-thai)", "serif"],
        "label-caps": ["var(--font-manrope)", "var(--font-noto-thai)", "sans-serif"],
        "display-lg-mobile": ["var(--font-playfair)", "var(--font-noto-thai)", "serif"],
        "body-lg": ["var(--font-manrope)", "var(--font-noto-thai)", "sans-serif"],
        "body-md": ["var(--font-manrope)", "var(--font-noto-thai)", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "thai-support": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
