import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#1b1607",
        "on-tertiary-container": "#cfe6d8",
        "on-primary": "#1b1607",
        "on-surface": "#f3ecdd",
        "on-primary-container": "#f7e9c4",
        "error-container": "#47161a",
        tertiary: "#79b08d",
        background: "#0b1210",
        "inverse-primary": "#4a3b12",
        "on-secondary": "#e9efe6",
        "primary-fixed": "#e4c876",
        "on-tertiary-fixed": "#0e1a13",
        error: "#e5484d",
        secondary: "#1e3a2c",
        "surface-container-high": "#182620",
        "on-secondary-container": "#cfe0c8",
        outline: "#63705f",
        "surface-tint": "#b4923b",
        surface: "#0b1210",
        "on-surface-variant": "#a9a192",
        "on-primary-fixed": "#241c08",
        "on-tertiary": "#0e1a13",
        "surface-container": "#131e1a",
        "on-error": "#2a0a0a",
        "surface-container-low": "#0f1714",
        "tertiary-container": "#1f3a2c",
        "on-error-container": "#ffdad9",
        "on-primary-fixed-variant": "#4a3b12",
        "on-background": "#f3ecdd",
        primary: "#b4923b",
        "surface-container-lowest": "#050807",
        "on-secondary-fixed": "#eaf0e6",
        "secondary-container": "#16281f",
        "secondary-fixed": "#2a4736",
        "primary-container": "#7c6427",
        "tertiary-fixed-dim": "#4e7a5f",
        "primary-fixed-dim": "#c9a94e",
        "inverse-surface": "#f3ecdd",
        "surface-container-highest": "#1f3128",
        "on-secondary-fixed-variant": "#b9c7b2",
        "tertiary-fixed": "#6e9c7c",
        "secondary-fixed-dim": "#223b2d",
        "on-tertiary-fixed-variant": "#1a2e22",
        "outline-variant": "#2e3931",
        "surface-variant": "#29332d",
        "surface-bright": "#1b2723",
        "surface-dim": "#06090a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        gutter: "24px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-xl": "64px",
        "margin-desktop": "80px",
        "stack-lg": "32px",
        "margin-mobile": "20px",
      },
      maxWidth: {
        container: "1440px",
      },
      fontFamily: {
        "headline-md": ["var(--font-playfair)", "var(--font-noto-thai)", "serif"],
        "thai-support": ["var(--font-noto-thai)", "sans-serif"],
        "headline-lg": ["var(--font-playfair)", "var(--font-noto-thai)", "serif"],
        "display-lg": ["var(--font-playfair)", "var(--font-noto-thai)", "serif"],
        "label-caps": ["var(--font-manrope)", "var(--font-noto-thai)", "sans-serif"],
        "display-lg-mobile": ["var(--font-playfair)", "var(--font-noto-thai)", "serif"],
        "body-lg": ["var(--font-manrope)", "var(--font-noto-thai)", "sans-serif"],
        "body-md": ["var(--font-manrope)", "var(--font-noto-thai)", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "thai-support": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "display-lg-mobile": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
