import type { ProductImage } from "./site-data";

export type ProductCategory = "amulets" | "coins" | "collectibles";

export interface CatalogProduct {
  id: string;
  slug: string;
  category: ProductCategory;
  name: string;
  eyebrow: string;
  shortDescription: string;
  description: string;
  price: string;
  status: string;
  image: string;
  gallery: ProductImage[];
  year: string;
  material: string;
  condition: string;
  provenance: string;
}

export const categoryLabels: Record<ProductCategory, string> = {
  amulets: "พระเครื่อง",
  coins: "เหรียญ",
  collectibles: "ของสะสม",
};

export const categoryDescriptions: Record<ProductCategory, string> = {
  amulets: "พระพิมพ์ไทยและวัตถุมงคลคัดสรร พร้อมภาพประกอบสำหรับสอบถามและตรวจสอบองค์จริง",
  coins: "เหรียญไทย เหรียญกษาปณ์ และเหรียญที่ระลึกจากหลายยุคสมัย",
  collectibles: "ของเก่า ของหายาก และของสะสมที่มีเรื่องราวจากหลายยุคสมัย",
};

const galleryImage = (id: number, src: string, alt: string): ProductImage => ({ id, src, alt });

const galleryVideo = (id: number, src: string, poster: string, alt: string): ProductImage => ({
  id,
  src,
  poster,
  alt,
  kind: "video",
});

export const catalogProducts: CatalogProduct[] = [
  {
    id: "amulet-phra-pong-suphan",
    slug: "phra-pong-suphan",
    category: "amulets",
    name: "พระผงสุพรรณ พิมพ์คัดสรร",
    eyebrow: "พระเนื้อดิน · รายการอ้างอิง",
    shortDescription: "พระพิมพ์ทรงสามเหลี่ยมจากสายสุพรรณบุรี พร้อมภาพรายละเอียดทั้งด้านหน้าและด้านหลัง",
    description: "รายการภาพอ้างอิงสำหรับผู้ที่กำลังมองหาพระผงสุพรรณ ทีมงาน KORN & COINS จะตรวจสอบองค์จริง รุ่น เนื้อหา และสภาพก่อนสรุปราคาให้ทุกครั้ง",
    price: "สอบถามราคา",
    status: "คัดสรร",
    image: "/images/amulet-phra-pong-suphan.png",
    gallery: [
      galleryImage(0, "/images/amulet-phra-pong-suphan.png", "พระผงสุพรรณหลายองค์บนพื้นสีเข้ม"),
      galleryImage(1, "/images/amulet-closeup.jpg", "ภาพระยะใกล้ของพระเครื่องในตู้จัดแสดง"),
      galleryImage(2, "/images/amulet-boxes.jpg", "พระเครื่องหลายรุ่นในกล่องสะสม"),
      galleryImage(3, "/images/category-amulets-wikimedia.jpg", "พระเครื่องไทยหลายองค์จัดแสดงรวมกัน"),
    ],
    year: "รอตรวจสอบจากองค์จริง",
    material: "เนื้อดิน",
    condition: "รอตรวจสอบองค์จริง",
    provenance: "รับข้อมูลจากผู้สะสมและตรวจสอบก่อนซื้อขาย",
  },
  {
    id: "amulet-somdej-ketchaiyo",
    slug: "somdej-ketchaiyo",
    category: "amulets",
    name: "พระสมเด็จเกศไชโย",
    eyebrow: "พระเนื้อผง · รายการอ้างอิง",
    shortDescription: "พระสมเด็จทรงนิยมสำหรับนักสะสมที่ต้องการเริ่มต้นศึกษาพระเนื้อผงอย่างเป็นระบบ",
    description: "ภาพประกอบจากแหล่งเปิดเพื่อช่วยให้เห็นรูปทรงและรายละเอียดโดยรวม การซื้อขายจริงต้องอาศัยภาพองค์จริงและการตรวจสอบจากทีมงานก่อนทุกครั้ง",
    price: "สอบถามราคา",
    status: "กำลังตรวจสอบ",
    image: "/images/amulet-somdej-ketchaiyo.jpg",
    gallery: [
      galleryImage(0, "/images/amulet-somdej-ketchaiyo.jpg", "พระสมเด็จเกศไชโยในกรอบหลายองค์"),
      galleryImage(1, "/images/amulet-khun-paen-bang-krang.png", "พระเครื่องไทยหลายพิมพ์บนพื้นสีดำ"),
      galleryImage(2, "/images/amulet-boxes.jpg", "กล่องพระเครื่องและวัตถุมงคลหลายแบบ"),
    ],
    year: "รอตรวจสอบจากองค์จริง",
    material: "เนื้อผง",
    condition: "พิจารณาตามองค์จริง",
    provenance: "สอบถามประวัติและใบรับรองเพิ่มเติมได้",
  },
  {
    id: "amulet-khun-paen-bang-krang",
    slug: "khun-paen-bang-krang",
    category: "amulets",
    name: "ขุนแผนวัดบางกร่าง",
    eyebrow: "พระพิมพ์ไทย · รายการอ้างอิง",
    shortDescription: "พระพิมพ์เนื้อดินโทนเก่า เหมาะสำหรับผู้สะสมพระพิมพ์ไทยและผู้เริ่มต้นศึกษาพิมพ์ทรง",
    description: "นำเสนอเป็นรายการตัวอย่างเพื่อให้เห็นความหลากหลายของพระเครื่องในร้าน ราคาจริงขึ้นอยู่กับพิมพ์ เนื้อหา ความสมบูรณ์ และผลตรวจสอบองค์จริง",
    price: "สอบถามราคา",
    status: "มีข้อมูลให้สอบถาม",
    image: "/images/amulet-khun-paen-bang-krang.png",
    gallery: [
      galleryImage(0, "/images/amulet-khun-paen-bang-krang.png", "ขุนแผนวัดบางกร่างและพระพิมพ์ไทยหลายองค์"),
      galleryImage(1, "/images/amulet-phra-pong-suphan.png", "พระเนื้อดินสององค์สำหรับเปรียบเทียบพิมพ์"),
      galleryImage(2, "/images/amulet-closeup.jpg", "วัตถุมงคลในตู้จัดแสดงของร้าน"),
    ],
    year: "รอตรวจสอบจากองค์จริง",
    material: "เนื้อดิน",
    condition: "พิจารณาตามองค์จริง",
    provenance: "สอบถามประวัติการครอบครองได้",
  },
  {
    id: "amulet-case-selection",
    slug: "amulet-case-selection",
    category: "amulets",
    name: "ชุดพระเครื่องในกล่องสะสม",
    eyebrow: "ชุดสะสม · หลายองค์",
    shortDescription: "ชุดพระเครื่องหลายพิมพ์ในกล่อง เหมาะสำหรับผู้ที่ต้องการเริ่มจัดคอลเลกชันของตัวเอง",
    description: "คัดภาพจากบรรยากาศการจัดเก็บพระเครื่องของร้านเพื่อให้เห็นตัวเลือกหลายรูปแบบ ทีมงานช่วยแยกดูเป็นรายองค์และประเมินตามข้อมูลที่มีได้",
    price: "เริ่มต้นสอบถาม",
    status: "หลายรายการ",
    image: "/images/amulet-boxes.jpg",
    gallery: [
      galleryImage(0, "/images/amulet-boxes.jpg", "พระเครื่องหลายองค์ในกล่องกำมะหยี่"),
      galleryImage(1, "/images/shop-counter.jpg", "ตู้จัดแสดงพระและเหรียญภายในร้าน"),
      galleryImage(2, "/images/amulet-closeup.jpg", "รายละเอียดวัตถุมงคลในตู้จัดแสดง"),
    ],
    year: "หลากหลายรุ่น",
    material: "หลากหลายเนื้อ",
    condition: "แตกต่างกันตามองค์",
    provenance: "สอบถามองค์ที่สนใจและประวัติเพิ่มเติมได้",
  },
  {
    id: "amulet-display-selection",
    slug: "amulet-display-selection",
    category: "amulets",
    name: "พระเครื่องคัดสรรจากตู้จัดแสดง",
    eyebrow: "คอลเลกชันหน้าร้าน",
    shortDescription: "พระเครื่องหลายองค์จากคอลเลกชันหน้าร้าน สำหรับนัดชมและขอภาพองค์จริงเพิ่มเติม",
    description: "เลือกชมพระเครื่องหลากหลายรูปแบบจากภาพบรรยากาศหน้าร้านได้ที่นี่ หากสนใจองค์ใดเป็นพิเศษ ติดต่อทีมงานเพื่อขอภาพระยะใกล้และรายละเอียดได้",
    price: "สอบถามราคา",
    status: "นัดชมได้",
    image: "/images/amulets.jpg",
    gallery: [
      galleryImage(0, "/images/amulets.jpg", "พระเครื่องหลายองค์ในตู้จัดแสดง"),
      galleryImage(1, "/images/category-amulets-wikimedia.jpg", "พระเครื่องไทยหลายองค์แขวนเรียงกัน"),
      galleryImage(2, "/images/shop-side.jpg", "มุมจัดแสดงของสะสมภายในร้าน"),
    ],
    year: "หลากหลายยุคสมัย",
    material: "หลากหลายเนื้อ",
    condition: "ตรวจสอบแยกตามองค์",
    provenance: "มีข้อมูลประกอบตามรายการที่สอบถาม",
  },
  {
    id: "coin-red-case-selection",
    slug: "coin-red-case-selection",
    category: "coins",
    name: "เหรียญทองในตลับแดง",
    eyebrow: "เหรียญสะสม · หลายรายการ",
    shortDescription: "เหรียญทองและเหรียญที่ระลึกหลายแบบ จัดเก็บในตลับเพื่อช่วยรักษาสภาพ",
    description: "รวมภาพเหรียญในคอลเลกชันสำหรับผู้ที่กำลังมองหาเหรียญไทยและเหรียญที่ระลึก ทีมงานจะช่วยตรวจสอบปี รุ่น โลหะ และสภาพก่อนเสนอราคา",
    price: "สอบถามราคา",
    status: "หลายรายการ",
    image: "/images/coin-red-case.jpg",
    gallery: [
      galleryImage(0, "/images/coin-red-case.jpg", "เหรียญทองจำนวนมากในตลับสีแดง"),
      galleryImage(1, "/images/coins-overhead.jpg", "เหรียญสะสมจำนวนมากบนถาดสีแดง"),
      galleryImage(2, "/images/coin-medallion.jpg", "เหรียญที่ระลึกในกล่องสะสม"),
    ],
    year: "หลายยุคสมัย",
    material: "โลหะหลายชนิด",
    condition: "คัดสภาพตามรายการ",
    provenance: "สอบถามภาพและข้อมูลรายเหรียญได้",
  },
  {
    id: "thai-coin-overhead-selection",
    slug: "thai-coin-overhead-selection",
    category: "coins",
    name: "เหรียญไทยและเหรียญที่ระลึก",
    eyebrow: "เหรียญหมุนเวียน · เหรียญสะสม",
    shortDescription: "ชุดเหรียญหลากหลายขนาด เหมาะสำหรับผู้เริ่มต้นและนักสะสมที่กำลังจัดหมวดหมู่",
    description: "เหรียญแต่ละรายการมีรายละเอียดแตกต่างกันทั้งปีผลิต โลหะ และสภาพ ภาพนี้ใช้แสดงภาพรวมของสินค้าที่ร้านรับซื้อและจำหน่าย",
    price: "เริ่มต้น 250 บาท",
    status: "พร้อมสอบถาม",
    image: "/images/coins-overhead.jpg",
    gallery: [
      galleryImage(0, "/images/coins-overhead.jpg", "เหรียญไทยหลายชนิดบนถาดสีแดง"),
      galleryImage(1, "/images/category-coins-wikimedia.jpg", "เหรียญไทยหลายชนิดจัดแสดงรวมกัน"),
      galleryImage(2, "/images/coin-red-case.jpg", "เหรียญหลายแบบในตลับเก็บรักษา"),
    ],
    year: "รัชกาลและยุคสมัยหลากหลาย",
    material: "ทองแดง ทองเหลือง และโลหะผสม",
    condition: "มีทั้งหมุนเวียนและสะสม",
    provenance: "สอบถามรายละเอียดและจำนวนที่มีได้",
  },
  {
    id: "coin-medallion-collection",
    slug: "coin-medallion-collection",
    category: "coins",
    name: "เหรียญที่ระลึกในกล่องสะสม",
    eyebrow: "เหรียญที่ระลึก · พร้อมกล่อง",
    shortDescription: "เหรียญที่ระลึกพร้อมกล่อง เหมาะสำหรับเก็บเป็นของที่ระลึกหรือเริ่มสะสมตามโอกาสสำคัญ",
    description: "คัดรายการที่มีบรรจุภัณฑ์และกล่องประกอบไว้ให้เลือกหลายรูปแบบ ทีมงานช่วยตรวจสอบรายละเอียดบนเหรียญและความครบถ้วนของชุดได้",
    price: "สอบถามราคา",
    status: "มีจำนวนจำกัด",
    image: "/images/coin-medallion.jpg",
    gallery: [
      galleryImage(0, "/images/coin-medallion.jpg", "เหรียญที่ระลึกในกล่องสะสม"),
      galleryImage(1, "/images/coin-display.jpg", "เหรียญและวัตถุมงคลในตู้จัดแสดง"),
      galleryImage(2, "/images/coin-red-case.jpg", "เหรียญหลายรุ่นในตลับสีแดง"),
    ],
    year: "ตรวจสอบตามเหรียญ",
    material: "โลหะตามรุ่น",
    condition: "พร้อมกล่องตามรายการ",
    provenance: "สอบถามเอกสารและอุปกรณ์ประกอบได้",
  },
  {
    id: "coin-display-selection",
    slug: "coin-display-selection",
    category: "coins",
    name: "เหรียญสะสมจากตู้จัดแสดง",
    eyebrow: "คอลเลกชันเหรียญหน้าร้าน",
    shortDescription: "ภาพรวมเหรียญหลายชนิดที่จัดแสดงในร้าน เหมาะสำหรับนัดชมและคัดเลือกเป็นชุด",
    description: "รายการนี้ช่วยให้เห็นบรรยากาศและความหลากหลายของเหรียญภายในร้าน เมื่อต้องการซื้อขายจริงทีมงานจะส่งภาพและข้อมูลรายเหรียญให้ตรวจสอบก่อน",
    price: "สอบถามราคา",
    status: "นัดชมได้",
    image: "/images/coin-display.jpg",
    gallery: [
      galleryImage(0, "/images/coin-display.jpg", "เหรียญจำนวนมากในตู้จัดแสดง"),
      galleryImage(1, "/images/coins.jpg", "เหรียญสะสมหลากหลายรูปแบบ"),
      galleryImage(2, "/images/coins-overhead.jpg", "เหรียญสะสมบนถาดสีแดง"),
    ],
    year: "หลายยุคสมัย",
    material: "โลหะหลายชนิด",
    condition: "ตรวจสอบแยกตามรายการ",
    provenance: "นัดหมายเข้าชมและขอข้อมูลเพิ่มเติมได้",
  },
  {
    id: "collectible-amulet-cases",
    slug: "collectible-amulet-cases",
    category: "collectibles",
    name: "กล่องและตลับของสะสม",
    eyebrow: "อุปกรณ์สะสม · ของเก่า",
    shortDescription: "กล่อง ตลับ และบรรจุภัณฑ์เก่าสำหรับจัดเก็บพระเครื่องและเหรียญสะสม",
    description: "ของสะสมบางชิ้นมีคุณค่าจากกล่องและรายละเอียดงานเก็บรักษา รายการนี้รวมภาพหลายแบบเพื่อให้เลือกสอบถามตามขนาดและสภาพที่ต้องการ",
    price: "สอบถามราคา",
    status: "หลายแบบ",
    image: "/images/amulet-boxes.jpg",
    gallery: [
      galleryImage(0, "/images/amulet-boxes.jpg", "กล่องพระเครื่องหลายสีและหลายขนาด"),
      galleryImage(1, "/images/coin-red-case.jpg", "ตลับสีแดงสำหรับเก็บเหรียญ"),
      galleryImage(2, "/images/shop-counter.jpg", "ตู้จัดแสดงของสะสมภายในร้าน"),
    ],
    year: "หลากหลายช่วงเวลา",
    material: "ไม้ ผ้า และพลาสติก",
    condition: "มีทั้งเก่าและใหม่",
    provenance: "สอบถามขนาดและจำนวนที่มีได้",
  },
  {
    id: "collectible-shop-counter",
    slug: "collectible-shop-counter",
    category: "collectibles",
    name: "ของสะสมจากตู้หน้าร้าน",
    eyebrow: "ของเก่า · ของหายาก",
    shortDescription: "วัตถุสะสมหลากหลายชิ้นจากบรรยากาศหน้าร้าน สำหรับผู้ที่ชอบค้นหาของมีเรื่องราว",
    description: "คัดภาพจากหน้าร้านมาเป็นรายการตัวอย่าง ของจริงมีการหมุนเวียนอยู่เสมอ ติดต่อทีมงานเพื่อขอรายการล่าสุดและนัดชมได้",
    price: "สอบถามราคา",
    status: "หมุนเวียนทุกวัน",
    image: "/images/shop-counter.jpg",
    gallery: [
      galleryImage(0, "/images/shop-counter.jpg", "ตู้หน้าร้านที่จัดแสดงพระและเหรียญ"),
      galleryImage(1, "/images/shop-side.jpg", "มุมจัดแสดงของสะสมภายในร้าน"),
      galleryImage(2, "/images/category-collectibles-wikimedia.jpg", "ตู้ไม้โบราณสำหรับจัดแสดงของสะสม"),
    ],
    year: "หลากหลายยุคสมัย",
    material: "หลากหลายวัสดุ",
    condition: "ตรวจสอบตามชิ้นงาน",
    provenance: "แจ้งข้อมูลที่มาเท่าที่มีในแต่ละรายการ",
  },
  {
    id: "collectible-display-cabinet",
    slug: "collectible-display-cabinet",
    category: "collectibles",
    name: "ตู้จัดแสดงของสะสมวินเทจ",
    eyebrow: "เฟอร์นิเจอร์สะสม · ของเก่า",
    shortDescription: "ตู้จัดแสดงสไตล์วินเทจสำหรับผู้ที่ต้องการเพิ่มบรรยากาศให้คอลเลกชันที่บ้าน",
    description: "รายการภาพอ้างอิงสำหรับตู้และเฟอร์นิเจอร์จัดแสดงของสะสม สามารถสอบถามเรื่องขนาด วัสดุ และการขนส่งกับทีมงานได้",
    price: "สอบถามราคา",
    status: "สอบถามสต็อก",
    image: "/images/category-collectibles-wikimedia.jpg",
    gallery: [
      galleryImage(0, "/images/category-collectibles-wikimedia.jpg", "ตู้จัดแสดงไม้โบราณสไตล์วินเทจ"),
      galleryImage(1, "/images/shop-side.jpg", "บรรยากาศมุมจัดแสดงของสะสม"),
      galleryImage(2, "/images/shop-counter.jpg", "ตู้จัดแสดงภายในร้าน KORN & COINS"),
    ],
    year: "ประมาณต้นคริสต์ศตวรรษที่ 19 ตามภาพอ้างอิง",
    material: "ไม้และวัสดุตกแต่ง",
    condition: "ตรวจสอบสภาพชิ้นจริง",
    provenance: "สอบถามรายละเอียดแหล่งที่มาได้",
  },
  {
    id: "collectible-banknote-set",
    slug: "collectible-banknote-set",
    category: "collectibles",
    name: "ธนบัตรและเอกสารสะสม",
    eyebrow: "กระดาษสะสม · ของเก่า",
    shortDescription: "ธนบัตรและเอกสารสะสมสำหรับคนที่ชอบเรื่องราวทางประวัติศาสตร์และการออกแบบ",
    description: "สินค้าในหมวดนี้มีรายละเอียดเรื่องปี พิมพ์ และสภาพกระดาษที่แตกต่างกัน ติดต่อทีมงานเพื่อขอภาพหน้า–หลังและข้อมูลรายใบได้",
    price: "เริ่มต้น 300 บาท",
    status: "พร้อมสอบถาม",
    image: "/images/banknotes.jpg",
    gallery: [
      galleryImage(0, "/images/banknotes.jpg", "ธนบัตรสะสมหลายแบบ"),
      galleryImage(1, "/images/coin-display.jpg", "ของสะสมในตู้จัดแสดง"),
      galleryImage(2, "/images/shop-side.jpg", "บรรยากาศพื้นที่จัดแสดงในร้าน"),
    ],
    year: "หลายยุคสมัย",
    material: "กระดาษและวัสดุพิมพ์",
    condition: "ตรวจสอบตามสภาพกระดาษ",
    provenance: "สอบถามประวัติและรายละเอียดรายใบได้",
  },
  {
    id: "collectible-pp-calatrava-pilot",
    slug: "pp-calatrava-pilot-travel-time",
    category: "collectibles",
    name: "Patek Philippe Calatrava Pilot Travel Time โรสโกลด์",
    eyebrow: "นาฬิกาสะสม · ภาพสินค้าจริง",
    shortDescription: "นาฬิกาสไตล์นักบิน ตัวเรือนทองโรสโกลด์ หน้าปัดโทนเข้ม พร้อมระบบสองเวลา LOCAL / HOME และสายหนังสีน้ำตาล",
    description: "ภาพถ่ายจากเรือนจริงหน้าร้าน ตัวเรือนทองโรสโกลด์ทรงนักบิน หน้าปัดไล่เฉดเข้ม เลขอารบิกเรืองแสง เข็มและปุ่มปรับเวลาสองตำแหน่งฝั่งซ้าย มีหน้าปัดย่อยแสดงวันที่ สายหนังสีน้ำตาลเย็บด้ายขาว การซื้อขายจริงนัดชมเรือน ตรวจสภาพ และตรวจชุดกล่อง–ใบรับประกันก่อนสรุปราคาทุกครั้ง",
    price: "สอบถามราคา",
    status: "ภาพสินค้าจริง",
    image: "/images/pp-calatrava-pilot-01.jpg",
    gallery: [
      galleryImage(0, "/images/pp-calatrava-pilot-01.jpg", "Patek Philippe Calatrava Pilot Travel Time ตัวเรือนทองโรสโกลด์ สายหนังน้ำตาล วางบนผ้าเช็ดนาฬิกา"),
      galleryImage(1, "/images/pp-calatrava-pilot-02.jpg", "ภาพระยะใกล้หน้าปัด Patek Philippe Pilot Travel Time เห็นหน้าปัดย่อยวันที่และช่อง LOCAL / HOME"),
    ],
    year: "รอตรวจสอบจากเรือนจริง",
    material: "ตัวเรือนทองโรสโกลด์ · สายหนัง",
    condition: "พิจารณาตามเรือนจริง",
    provenance: "สอบถามชุดกล่อง ใบรับประกัน และประวัติเรือนเพิ่มเติมได้",
  },
  {
    id: "collectible-pp-aquanaut-chrono",
    slug: "pp-aquanaut-chronograph",
    category: "collectibles",
    name: "Patek Philippe Aquanaut Chronograph สตีล",
    eyebrow: "นาฬิกาสะสม · มีคลิปวิดีโอ",
    shortDescription: "Aquanaut โครโนกราฟ ตัวเรือนสตีล หน้าปัดลายนูนสีเข้ม จับเวลาเข็มสีส้ม พร้อมสายยางสีดำ มีคลิปวิดีโอประกอบ",
    description: "ภาพนิ่งและคลิปวิดีโอจากเรือนจริงในกล่อง Patek Philippe ตัวเรือนสตีลทรงเบาะ หน้าปัดลายนูนสีเข้ม เข็มจับเวลาและสเกลสีส้มตัดกับหน้าปัด ช่องวันที่ที่ตำแหน่ง 3 นาฬิกา สายยางสีดำลายเดียวกับหน้าปัด นัดชมเรือนจริงและตรวจชุดอุปกรณ์ก่อนซื้อขายได้",
    price: "สอบถามราคา",
    status: "ภาพสินค้าจริง",
    image: "/images/pp-aquanaut-chrono-01.jpg",
    gallery: [
      galleryImage(0, "/images/pp-aquanaut-chrono-01.jpg", "Patek Philippe Aquanaut Chronograph ตัวเรือนสตีล สายยางดำ ในกล่อง Patek Philippe"),
      galleryVideo(1, "/videos/pp-aquanaut-chrono.mp4", "/images/pp-aquanaut-chrono-poster.jpg", "คลิปวิดีโอ Patek Philippe Aquanaut Chronograph หมุนดูรอบเรือนในกล่อง"),
    ],
    year: "รอตรวจสอบจากเรือนจริง",
    material: "ตัวเรือนสตีล · สายยาง",
    condition: "พิจารณาตามเรือนจริง",
    provenance: "สอบถามชุดกล่อง ใบรับประกัน และประวัติเรือนเพิ่มเติมได้",
  },
  {
    id: "collectible-fm-vanguard-dragon",
    slug: "franck-muller-vanguard-dragon",
    category: "collectibles",
    name: "Franck Muller Vanguard มังกร หน้าปัดแดง",
    eyebrow: "นาฬิกาสะสม · ภาพสินค้าจริง",
    shortDescription: "Vanguard ทรงตอนโน หน้าปัดสีแดง ลายมังกรนูนสีเงิน เลขประยุกต์เรืองแสง ช่องวันที่ และสายหนังสีดำเย็บด้ายแดง",
    description: "ภาพถ่ายจากเรือนจริง ตัวเรือนทรงตอนโนขนาดใหญ่ หน้าปัดสีแดงประดับมังกรนูนสีเงิน หลักเลขประยุกต์เรืองแสง สเกลรอบหน้าปัดสไตล์เข็มทิศ ช่องวันที่ใกล้ตำแหน่ง 4–5 นาฬิกา สายหนังลายจระเข้สีดำเย็บด้ายแดง เม็ดมะยมฝังยางแดง นัดชมเรือนจริงและตรวจสภาพก่อนสรุปราคาได้",
    price: "สอบถามราคา",
    status: "ภาพสินค้าจริง",
    image: "/images/franck-muller-vanguard-dragon-01.jpg",
    gallery: [
      galleryImage(0, "/images/franck-muller-vanguard-dragon-01.jpg", "Franck Muller Vanguard หน้าปัดแดงลายมังกร ถือบนมือ"),
      galleryImage(1, "/images/franck-muller-vanguard-dragon-02.jpg", "ภาพระยะใกล้หน้าปัด Franck Muller Vanguard เห็นมังกรนูนและช่องวันที่"),
    ],
    year: "รอตรวจสอบจากเรือนจริง",
    material: "ตัวเรือนสตีล · สายหนัง",
    condition: "พิจารณาตามเรือนจริง",
    provenance: "สอบถามชุดกล่อง ใบรับประกัน และประวัติเรือนเพิ่มเติมได้",
  },
  {
    id: "collectible-ap-royal-oak-offshore",
    slug: "ap-royal-oak-offshore-chronograph",
    category: "collectibles",
    name: "Audemars Piguet Royal Oak Offshore Chronograph สตีล",
    eyebrow: "นาฬิกาสะสม · ภาพสินค้าจริง",
    shortDescription: "Royal Oak Offshore โครโนกราฟ ตัวเรือนสตีล ขอบแปดเหลี่ยมยึดสกรู หน้าปัดลาย tapisserie สีเข้ม สายหนังสีดำเย็บด้ายแดง",
    description: "ภาพถ่ายจากเรือนจริงในกล่อง ตัวเรือนสตีลทรงขอบแปดเหลี่ยมยึดสกรูหกเหลี่ยม หน้าปัดลายตารางนูนสีเข้ม โลโก้ AP กลางหน้าปัด หน้าปัดย่อยจับเวลา 60 SECS และ MNS สเกล tachymeter ช่องวันที่ที่ตำแหน่ง 3 นาฬิกา สายหนังลายจระเข้สีดำเย็บด้ายแดง บานพับสตีล นัดชมเรือนจริงและตรวจชุดอุปกรณ์ก่อนซื้อขายได้",
    price: "สอบถามราคา",
    status: "ภาพสินค้าจริง",
    image: "/images/ap-royal-oak-offshore-chrono-01.jpg",
    gallery: [
      galleryImage(0, "/images/ap-royal-oak-offshore-chrono-01.jpg", "Audemars Piguet Royal Oak Offshore Chronograph ตัวเรือนสตีล สายหนังดำเย็บด้ายแดง ในกล่อง"),
      galleryImage(1, "/images/ap-royal-oak-offshore-chrono-02.jpg", "ภาพระยะใกล้หน้าปัด Royal Oak Offshore เห็นลาย tapisserie หน้าปัดย่อยจับเวลา และช่องวันที่"),
    ],
    year: "รอตรวจสอบจากเรือนจริง",
    material: "ตัวเรือนสตีล · สายหนัง",
    condition: "พิจารณาตามเรือนจริง",
    provenance: "สอบถามชุดกล่อง ใบรับประกัน และประวัติเรือนเพิ่มเติมได้",
  },
  {
    id: "collectible-pp-aquanaut-luce-green",
    slug: "pp-aquanaut-luce-green-diamond",
    category: "collectibles",
    name: "Patek Philippe Aquanaut Luce หน้าปัดเขียว ขอบเพชร",
    eyebrow: "นาฬิกาสะสม · ภาพสินค้าจริง",
    shortDescription: "Aquanaut Luce ตัวเรือนทรงเบาะ ขอบตัวเรือนฝังเพชร หน้าปัดเขียวลายนูน ช่องวันที่ และสายยางสีเขียว",
    description: "ภาพถ่ายจากเรือนจริง ตัวเรือนทรงเบาะพร้อมขอบฝังเพชรรอบวง หน้าปัดสีเขียวลายนูนเอกลักษณ์ Aquanaut หลักเลขและหลักชั่วโมงเรืองแสง ช่องวันที่ที่ตำแหน่ง 3 นาฬิกา สายยางสีเขียวเข้าชุด นัดชมเรือนจริง ตรวจเพชร และตรวจชุดอุปกรณ์ก่อนสรุปราคาได้",
    price: "สอบถามราคา",
    status: "ภาพสินค้าจริง",
    image: "/images/pp-aquanaut-green-diamond-01.jpg",
    gallery: [
      galleryImage(0, "/images/pp-aquanaut-green-diamond-01.jpg", "Patek Philippe Aquanaut Luce หน้าปัดเขียว ขอบตัวเรือนฝังเพชร สายยางเขียว"),
    ],
    year: "รอตรวจสอบจากเรือนจริง",
    material: "ตัวเรือนสตีลฝังเพชร · สายยาง",
    condition: "พิจารณาตามเรือนจริง",
    provenance: "สอบถามชุดกล่อง ใบรับประกัน และใบตรวจเพชรเพิ่มเติมได้",
  },
  {
    id: "collectible-pp-twenty-four",
    slug: "pp-twenty-four-diamond",
    category: "collectibles",
    name: "Patek Philippe Twenty~4 เรือนสุภาพสตรี ขอบเพชร",
    eyebrow: "นาฬิกาสะสม · มีคลิปวิดีโอ",
    shortDescription: "Twenty~4 ทรงมองต์ ตัวเรือนด้านข้างฝังเพชร หน้าปัดมุกขาว หลักโรมันและหลักเพชร พร้อมสายสตีล มีคลิปวิดีโอประกอบ",
    description: "คลิปวิดีโอจากเรือนจริง ตัวเรือนทรงสี่เหลี่ยมสไตล์ manchette ด้านข้างฝังเพชรสองแถว หน้าปัดมุกขาว หลักเลขโรมัน XII และ VI คู่กับหลักเพชร สายสตีลถักปล้อง เหมาะสำหรับสุภาพสตรี นัดชมเรือนจริง ตรวจเพชร และตรวจชุดอุปกรณ์ก่อนสรุปราคาได้",
    price: "สอบถามราคา",
    status: "ภาพสินค้าจริง",
    image: "/images/pp-twenty4-ladies-poster.jpg",
    gallery: [
      galleryVideo(0, "/videos/pp-twenty4-ladies.mp4", "/images/pp-twenty4-ladies-poster.jpg", "คลิปวิดีโอ Patek Philippe Twenty~4 เรือนสุภาพสตรี ขอบเพชร สายสตีล"),
    ],
    year: "รอตรวจสอบจากเรือนจริง",
    material: "ตัวเรือนสตีลฝังเพชร · สายสตีล",
    condition: "พิจารณาตามเรือนจริง",
    provenance: "สอบถามชุดกล่อง ใบรับประกัน และใบตรวจเพชรเพิ่มเติมได้",
  },
  {
    id: "collectible-diamond-gemstone-jewelry",
    slug: "diamond-gemstone-jewelry-selection",
    category: "collectibles",
    name: "เครื่องประดับเพชรและอัญมณีคัดสรร",
    eyebrow: "เครื่องประดับ · มีคลิปวิดีโอ",
    shortDescription: "ถาดแหวนและจี้เพชรพร้อมพลอยสีหลากหลาย ทั้งไพลิน ทับทิม โอปอล หยก และไข่มุก มีคลิปวิดีโอรวมให้ชม",
    description: "คลิปวิดีโอรวมเครื่องประดับหลายชิ้นจากหน้าร้าน มีทั้งแหวนเพชร แหวนพลอยสี จี้ และเข็มกลัด ตัวเรือนทองและทองขาว แต่ละชิ้นมีรายละเอียดน้ำหนักทอง ชนิดพลอย และขนาดแตกต่างกัน สอบถามชิ้นที่สนใจเพื่อขอภาพระยะใกล้ ใบตรวจอัญมณี และราคารายชิ้นได้",
    price: "สอบถามราคา",
    status: "หลายรายการ",
    image: "/images/diamond-gemstone-jewelry-tray-poster.jpg",
    gallery: [
      galleryVideo(0, "/videos/diamond-gemstone-jewelry-tray.mp4", "/images/diamond-gemstone-jewelry-tray-poster.jpg", "คลิปวิดีโอถาดเครื่องประดับเพชรและพลอยสีหลายชิ้น"),
    ],
    year: "หลากหลายช่วงเวลา",
    material: "ทอง ทองขาว เพชร และพลอยสี",
    condition: "แตกต่างกันตามชิ้น",
    provenance: "สอบถามใบตรวจอัญมณีและรายละเอียดรายชิ้นได้",
  },
  {
    id: "collectible-antique-gold-diamond-set",
    slug: "antique-gold-diamond-jewelry-set",
    category: "collectibles",
    name: "ชุดเครื่องประดับทองโบราณฝังเพชรซีก",
    eyebrow: "เครื่องประดับโบราณ · มีคลิปวิดีโอ",
    shortDescription: "ชุดทองโบราณฝังเพชรซีก ประกอบด้วยสร้อยคอ แหวน และกำไล งานฝังมือลายละเอียด มีคลิปวิดีโอแยกแต่ละชิ้น",
    description: "คลิปวิดีโอจากงานจริง เครื่องประดับทองโบราณฝังเพชรซีก (เพชรเจียระไนแบบเก่า) ลายฝังกระจุกดอก งานประณีตทั้งชุด — สร้อยคอตัวเรือนใหญ่ แหวนหน้ากว้าง และกำไลข้อมือ แต่ละชิ้นน้ำหนักทองและจำนวนเพชรต่างกัน สอบถามเพื่อขอชั่งน้ำหนัก ตรวจเนื้อทอง และราคารายชิ้นได้",
    price: "สอบถามราคา",
    status: "หลายรายการ",
    image: "/images/antique-gold-diamond-necklace-poster.jpg",
    gallery: [
      galleryVideo(0, "/videos/antique-gold-diamond-necklace.mp4", "/images/antique-gold-diamond-necklace-poster.jpg", "คลิปวิดีโอสร้อยคอทองโบราณฝังเพชรซีก"),
      galleryVideo(1, "/videos/antique-gold-diamond-ring.mp4", "/images/antique-gold-diamond-ring-poster.jpg", "คลิปวิดีโอแหวนทองโบราณฝังเพชรซีกสวมบนนิ้ว"),
      galleryVideo(2, "/videos/antique-gold-diamond-bangle.mp4", "/images/antique-gold-diamond-bangle-poster.jpg", "คลิปวิดีโอกำไลทองโบราณฝังเพชรซีกสวมบนข้อมือ"),
    ],
    year: "หลากหลายยุคสมัย",
    material: "ทอง และเพชรซีก",
    condition: "แตกต่างกันตามชิ้น",
    provenance: "สอบถามน้ำหนักทองและรายละเอียดรายชิ้นได้",
  },
  {
    id: "collectible-antique-silver-filigree",
    slug: "antique-silver-filigree-ware",
    category: "collectibles",
    name: "เครื่องเงินโบราณลายฉลุ",
    eyebrow: "ของเก่า · มีคลิปวิดีโอ",
    shortDescription: "เครื่องเงินโบราณงานลายฉลุ หูหิ้วขึ้นรูปสัตว์ พร้อมของสะสมเนื้อเงินอื่นในตู้ มีคลิปวิดีโอให้ชม",
    description: "คลิปวิดีโอจากตู้จัดแสดง เครื่องเงินโบราณงานลายฉลุละเอียด หูหิ้วขึ้นรูปเป็นสัตว์ พร้อมของสะสมเนื้อเงินและเหรียญที่ระลึกในกล่องอีกหลายรายการในฉากหลัง สอบถามชิ้นที่สนใจเพื่อขอภาพระยะใกล้ ชั่งน้ำหนัก และรายละเอียดที่มาได้",
    price: "สอบถามราคา",
    status: "หลายรายการ",
    image: "/images/antique-silver-filigree-ware-poster.jpg",
    gallery: [
      galleryVideo(0, "/videos/antique-silver-filigree-ware.mp4", "/images/antique-silver-filigree-ware-poster.jpg", "คลิปวิดีโอเครื่องเงินโบราณลายฉลุ หูหิ้วขึ้นรูปสัตว์ ในตู้จัดแสดง"),
    ],
    year: "หลากหลายยุคสมัย",
    material: "เนื้อเงิน",
    condition: "ตรวจสอบตามชิ้นงาน",
    provenance: "แจ้งข้อมูลที่มาเท่าที่มีในแต่ละรายการ",
  },
  {
    id: "coin-medal-rama9-queen-sirikit",
    slug: "medal-rama9-queen-sirikit-silver",
    category: "coins",
    name: "เหรียญที่ระลึกพระบรมฉายาลักษณ์คู่ เนื้อเงิน",
    eyebrow: "เหรียญที่ระลึก · เนื้อเงิน",
    shortDescription: "เหรียญที่ระลึกทรงโค้ง เนื้อเงิน นูนพระบรมฉายาลักษณ์คู่ ผิวเหรียญขึ้นคราบเก่าตามกาลเวลา พร้อมห่วงสำหรับห้อย",
    description: "ภาพถ่ายจากเหรียญจริง เหรียญที่ระลึกทรงโค้งด้านบน เนื้อเงิน ด้านหน้านูนพระบรมฉายาลักษณ์คู่หันข้าง ผิวเหรียญขึ้นคราบรุ้งและคราบเก่าตามอายุ มีห่วงเชื่อมสำหรับร้อยสร้อย ทีมงานตรวจสอบเนื้อโลหะ ปีจัดสร้าง และความสมบูรณ์ก่อนเสนอราคาทุกครั้ง",
    price: "สอบถามราคา",
    status: "กำลังตรวจสอบ",
    image: "/images/medal-rama9-queen-sirikit-01.jpg",
    gallery: [
      galleryImage(0, "/images/medal-rama9-queen-sirikit-01.jpg", "เหรียญที่ระลึกทรงโค้งเนื้อเงิน นูนพระบรมฉายาลักษณ์คู่ ผิวขึ้นคราบเก่า"),
    ],
    year: "รอตรวจสอบจากเหรียญจริง",
    material: "เนื้อเงิน",
    condition: "พิจารณาตามเหรียญจริง",
    provenance: "สอบถามปีจัดสร้างและวาระที่ระลึกเพิ่มเติมได้",
  },
  {
    id: "coin-graded-collection-slabs",
    slug: "graded-coin-collection-slabs",
    category: "coins",
    name: "คอลเลกชันเหรียญและเหรียญทองในตลับเกรดดิ้ง (NGC / PCGS)",
    eyebrow: "เหรียญสะสม · เข้าตลับเกรด",
    shortDescription: "เหรียญไทยและเหรียญทองจำนวนมากบรรจุตลับเกรดดิ้ง NGC และ PCGS พร้อมป้ายระบุรุ่นและเกรด",
    description: "ภาพรวมคอลเลกชันเหรียญและเหรียญทองที่ผ่านการเข้าตลับเกรดดิ้งจาก NGC และ PCGS จัดเรียงพร้อมป้ายระบุรุ่น ปี และเกรด มีทั้งเหรียญที่ระลึก เหรียญกษาปณ์ และเหรียญทองหลายวาระ สอบถามรายการและเกรดที่สนใจเพื่อขอภาพเฉพาะตลับและราคารายเหรียญได้",
    price: "สอบถามราคา",
    status: "หลายรายการ",
    image: "/images/coin-collection-graded-slabs-01.jpg",
    gallery: [
      galleryImage(0, "/images/coin-collection-graded-slabs-01.jpg", "เหรียญและเหรียญทองจำนวนมากในตลับเกรดดิ้ง NGC และ PCGS จัดเรียงเป็นแถว"),
    ],
    year: "หลายยุคสมัย",
    material: "เนื้อทอง เงิน และโลหะผสม",
    condition: "ระบุเกรดบนตลับแต่ละรายการ",
    provenance: "สอบถามหมายเลขตลับและใบเกรดรายเหรียญได้",
  },
  {
    id: "coin-medal-fao-ceres-sirikit",
    slug: "medal-fao-ceres-sirikit-gold-pendant",
    category: "coins",
    name: "เหรียญทอง FAO Ceres สมเด็จพระบรมราชินีนาถ เลี่ยมกรอบเพชร",
    eyebrow: "เหรียญทอง · เลี่ยมกรอบเพชร",
    shortDescription: "เหรียญทอง FAO Ceres นูนพระบรมฉายาลักษณ์สมเด็จพระบรมราชินีนาถ เลี่ยมกรอบทองฝังเพชรลายไทยพร้อมช่อชัยพฤกษ์",
    description: "ภาพถ่ายจากชิ้นจริง เหรียญทองชุด FAO Ceres สลัก CERES · FAO · ROME และ SIRIKIT OF THAILAND ด้านหน้านูนพระบรมฉายาลักษณ์ นำมาเลี่ยมกรอบทองฝังเพชรเต็มวง ประดับลายไทยด้านบนและช่อชัยพฤกษ์ด้านล่าง สอบถามน้ำหนักทองเหรียญ น้ำหนักเพชรกรอบ และใบรับรองเพิ่มเติมได้",
    price: "สอบถามราคา",
    status: "ภาพสินค้าจริง",
    image: "/images/medal-fao-ceres-sirikit-pendant-01.jpg",
    gallery: [
      galleryImage(0, "/images/medal-fao-ceres-sirikit-pendant-01.jpg", "เหรียญทอง FAO Ceres สมเด็จพระบรมราชินีนาถ เลี่ยมกรอบทองฝังเพชรลายไทยและช่อชัยพฤกษ์"),
    ],
    year: "รอตรวจสอบจากชิ้นจริง",
    material: "เหรียญทอง · กรอบทองฝังเพชร",
    condition: "พิจารณาตามชิ้นจริง",
    provenance: "สอบถามน้ำหนักทอง น้ำหนักเพชร และใบรับรองเพิ่มเติมได้",
  },
  {
    id: "amulet-gold-frame-pair",
    slug: "amulet-gold-frame-pair",
    category: "amulets",
    name: "พระเลี่ยมกรอบทองคู่ (พระขุนแผน · เหรียญพระเกจิ)",
    eyebrow: "พระเครื่อง · เลี่ยมกรอบทอง",
    shortDescription: "พระเลี่ยมกรอบทองสองรายการ องค์หนึ่งพิมพ์ขุนแผนงานปั๊มลายละเอียด อีกองค์เป็นเหรียญพระเกจิใต้กระจกครอบในกรอบทองลายไทย",
    description: "ภาพถ่ายจากองค์จริง มีสองรายการ องค์ซ้ายเป็นพระพิมพ์ขุนแผนทรงเรือนแก้ว งานปั๊มลายละเอียดเลี่ยมกรอบทอง องค์ขวาเป็นเหรียญรูปพระเกจิใต้กระจกครอบทรงโดม ประกบกรอบทองฉลุลายไทย ทีมงานตรวจสอบพิมพ์ เนื้อหา และเนื้อทองกรอบก่อนสรุปราคาทุกครั้ง",
    price: "สอบถามราคา",
    status: "ภาพสินค้าจริง",
    image: "/images/amulet-gold-frame-pair-01.jpg",
    gallery: [
      galleryImage(0, "/images/amulet-gold-frame-pair-01.jpg", "พระเลี่ยมกรอบทองสององค์บนฝ่ามือ องค์ซ้ายพิมพ์ขุนแผน องค์ขวาเหรียญพระเกจิใต้กระจกครอบ"),
    ],
    year: "รอตรวจสอบจากองค์จริง",
    material: "พระเครื่อง · กรอบทอง",
    condition: "พิจารณาตามองค์จริง",
    provenance: "สอบถามพิมพ์ รุ่น และน้ำหนักทองกรอบเพิ่มเติมได้",
  },
];

export const featuredProducts = catalogProducts.slice(0, 6);

export function isProductCategory(value: string | undefined): value is ProductCategory {
  return value === "amulets" || value === "coins" || value === "collectibles";
}

export function getProductBySlug(slug: string) {
  return catalogProducts.find((product) => product.slug === slug);
}

export function getRelatedProducts(product: CatalogProduct, limit = 4) {
  return catalogProducts
    .filter((candidate) => candidate.category === product.category && candidate.id !== product.id)
    .slice(0, limit);
}
